name: firebase_crashlytics_example
description: Demonstrates how to use the firebase_crashlytics plugin.

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics: ^12.0.2
  firebase_core:
    path: ../../../firebase_core/firebase_core
  firebase_crashlytics:
    path: ../
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
